# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml

stages:
- build
- test
- deploy

build:
  stage: build
  image: node:24-alpine
  before_script:
    - apk add --no-cache git python3 make g++
    - corepack enable
    - corepack prepare pnpm@10.19.0 --activate
  script:
    # Create required env files if they don't exist
    - |
      if [ ! -f apps/web/.env.local ]; then
        cp apps/web/.env.production apps/web/.env.local || touch apps/web/.env.local
      fi
    # Install dependencies
    - pnpm install --frozen-lockfile
    # Build with increased memory limit
    -  pnpm run build
  artifacts:
    paths:
      - apps/web/.next/
    expire_in: 1 hour

sast:
  stage: test

test:
  stage: test
  image: node:24-alpine
  script:
    - 'if [ ! -d "apps/web/.next" ]; then echo "Build failed: .next directory not found" && exit 1; fi'
    - 'if [ -z "$(ls -A apps/web/.next)" ]; then echo "Build failed: .next directory is empty" && exit 1; fi'
    - echo "Build completed successfully"
  dependencies:
    - build